### PR TITLE
fixes string interpolation failure for splines

### LINKED ISSUE #1380: string interpolation failure for splines
Found in tidymodels/tune#949

``` r
msg_test <- "Error in if (df < 0) { : missing value where TRUE/FALSE needed\n"
recipes:::spline_msg(msg_test)
#> Error in glue(str, .envir = .envir, .transformer = transformer, .cli = TRUE, : Expecting '}'
```

<sup>Created on 2024-10-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by topepo**
Closes #1380

``` r
msg_test <- "Error in if (df < 0) { : missing value where TRUE/FALSE needed\n"
recipes:::spline_msg(msg_test)
#> Error in `recipes:::spline_msg()`:
#> ! Error in if (df < 0) { : missing value where TRUE/FALSE needed
```

<sup>Created on 2024-10-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/spline_helpers.R [hunk 1]
```diff
@@ -46,6 +46,14 @@ spline2_create <- function(x, nm = "pred", .fn = "bSpline", df = 3, complete_set
 
 spline_msg <- function(x) {
   x <- as.character(x)
+  # Error messages can contain brackets (e.g. "Error in if (df < 0) { : missing value")
```
Comment (topepo) [inline R/spline_helpers.R:49]: A lot of comments so that future me/us will get the logic

File: R/spline_helpers.R [hunk 2]
```diff
@@ -46,6 +46,14 @@ spline2_create <- function(x, nm = "pred", .fn = "bSpline", df = 3, complete_set
...
+  # For glue string interpolation, the default open/close deliminators the
+  # brackets. cli_abort calls rlang's abort and that can't pass the arguments
+  # to change the delimiters but will ignore them if they are doubled. So we
+  # change "{" to "{{" (and also for close). Simultaneous substitution via
+  # `pattern = "(\\{)|(\\})"` produces poor results so we do them one at a time.
+  x <- gsub("(\\{)", "\\1\\1", x)
```
Comment (topepo) [inline R/spline_helpers.R:55]: Maybe this can be done in one shot?

File: DESCRIPTION [hunk 3]
```diff
@@ -1,6 +1,6 @@
 Package: recipes
 Title: Preprocessing and Feature Engineering Steps for Modeling
-Version: 1.1.0.9000
```
Comment (topepo) [inline DESCRIPTION:3]: So that I can updates tests/skips in tune

File: R/spline_helpers.R [hunk 4]
```diff
@@ -46,6 +46,14 @@ spline2_create <- function(x, nm = "pred", .fn = "bSpline", df = 3, complete_set
 
 spline_msg <- function(x) {
```
Comment (topepo) [inline R/spline_helpers.R:47]: For next week: pass the upstream caller env to avoid "Caused by error in `spline_msg()`:"

File: R/spline_helpers.R (hunk 2 above)
Comment (EmilHvitfeldt) [reply R/spline_helpers.R:55]: I'm perfectly fine to do it one at a time. we are throwing an error when this code is run so speed isn't an issue

**Review by EmilHvitfeldt — APPROVED** [review]

**Comment by EmilHvitfeldt** [comment]
looking good!
