### PR TITLE
make tidy.recipe work for zero step recipes

### LINKED ISSUE #867: tidy.recipe() throws error for zero-step recipes
`tidy.recipe()` should return a zero row tibble for empty recipes instead of throwing an error. This is making `step_detect()` error when used on empty recipes.

``` r
library(recipes)

recipe(~., data = mtcars) %>%
  step_center(all_predictors()) %>%
  tidy()
#> # A tibble: 1 × 6
#>   number operation type   trained skip  id          
#>    <int> <chr>     <chr>  <lgl>   <lgl> <chr>       
#> 1      1 step      center FALSE   FALSE center_uXNNk

recipe(~., data = mtcars) %>%
  tidy()
#> Error: No steps in recipe.
```

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
This PR aims to close #867.

Very simple change. I need it to fix `detect_step()` for https://github.com/tidymodels/recipes/issues/453

### CODE REVIEW

File: R/tidy.R [hunk 1]
```diff
@@ -55,8 +55,16 @@ tidy.recipe <- function(x, number = NA, id = NA, ...) {
...
+  if (num_oper == 0) {
+    return(
+      tibble(number = integer(),
+             operation = character(),
+             type = character(),
+             trained = logical(),
+             skip = logical(),
+             id = character())
+    )
+  }
```
Comment (DavisVaughan) [inline R/tidy.R:67]: What happens if we just remove this branch entirely? It looks like our usage of `vapply()` should set us up pretty well for the 0-step case to "just work" without special handling? Maybe one or two calls to some base R function might need to be tweaked.

Comment (EmilHvitfeldt) [reply R/tidy.R]: Good eye! Appears to work without further modification
